theme: jekyll-theme-minimal
title: "Who Dies the Most? The Tragic Truth About Movie Mortality"
description: "A data-driven exploration of movie character mortality."
show_downloads: True
navigation:
  - title: Home
    url: README.md
  # Remove this if you had an entry for data_story.md
#  - title: Data Story
#    url: data_story.md
